#ifdef VENDOR_EDIT
#xiang.fei@Multimedia.AudioDriver.Codec, 2018/03/12, add for codec
subdir-ccflags-y += -I$(srctree)/sound/soc/mediatek/common
snd-soc-tfa98xx-objs := tfa_container.o tfa98xx.o tfa_dsp.o tfa_init.o
obj-y += snd-soc-tfa98xx.o
#endif /* VENDOR_EDIT */